"""initial schema

Revision ID: d38eed28976a
Revises: 
Create Date: 2026-02-27 21:19:03.411955
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd38eed28976a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_prisma_migrations')
    op.alter_column('apartment_mix', 'apartment_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('apartment_mix_simulation_id_fkey', 'apartment_mix', type_='foreignkey')
    op.create_foreign_key(None, 'apartment_mix', 'simulations', ['simulation_id'], ['id'], ondelete='CASCADE')
    op.add_column('economic_parameters', sa.Column('ai_extraction_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('economic_parameters', 'sales_prices_by_use',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint('economic_parameters_simulation_id_fkey', 'economic_parameters', type_='foreignkey')
    op.create_foreign_key(None, 'economic_parameters', 'simulations', ['simulation_id'], ['id'], ondelete='CASCADE')
    op.add_column('planning_parameters', sa.Column('ai_extraction_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('planning_parameters_simulation_id_fkey', 'planning_parameters', type_='foreignkey')
    op.create_foreign_key(None, 'planning_parameters', 'simulations', ['simulation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('projects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('projects', 'tabu_extract_url')
    op.alter_column('simulation_results', 'entrepreneurial_profit', new_column_name='profit')
    op.drop_constraint('simulation_results_simulation_id_fkey', 'simulation_results', type_='foreignkey')
    op.create_foreign_key(None, 'simulation_results', 'simulations', ['simulation_id'], ['id'], ondelete='CASCADE')
    op.execute("CREATE TYPE simulationstatus AS ENUM ('DRAFT', 'AI_EXTRACTING', 'PENDING_REVIEW', 'APPROVED_FOR_CALC', 'COMPLETED')")
    op.add_column('simulations', sa.Column('status', sa.Enum('DRAFT', 'AI_EXTRACTING', 'PENDING_REVIEW', 'APPROVED_FOR_CALC', 'COMPLETED', name='simulationstatus', create_type=False), nullable=False, server_default='DRAFT'))
    op.alter_column('simulations', 'version_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('simulations', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('simulations_project_id_fkey', 'simulations', type_='foreignkey')
    op.create_foreign_key(None, 'simulations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'simulations', type_='foreignkey')
    op.create_foreign_key('simulations_project_id_fkey', 'simulations', 'projects', ['project_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('simulations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('simulations', 'version_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('simulations', 'status')
    op.add_column('simulation_results', sa.Column('entrepreneurial_profit', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'simulation_results', type_='foreignkey')
    op.create_foreign_key('simulation_results_simulation_id_fkey', 'simulation_results', 'simulations', ['simulation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('simulation_results', 'profit')
    op.add_column('projects', sa.Column('tabu_extract_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('projects', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('projects', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'planning_parameters', type_='foreignkey')
    op.create_foreign_key('planning_parameters_simulation_id_fkey', 'planning_parameters', 'simulations', ['simulation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('planning_parameters', 'ai_extraction_metadata')
    op.drop_constraint(None, 'economic_parameters', type_='foreignkey')
    op.create_foreign_key('economic_parameters_simulation_id_fkey', 'economic_parameters', 'simulations', ['simulation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('economic_parameters', 'sales_prices_by_use',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('economic_parameters', 'ai_extraction_metadata')
    op.drop_constraint(None, 'apartment_mix', type_='foreignkey')
    op.create_foreign_key('apartment_mix_simulation_id_fkey', 'apartment_mix', 'simulations', ['simulation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('apartment_mix', 'apartment_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='_prisma_migrations_pkey')
    )
    op.drop_table('documents')
    # ### end Alembic commands ###
