"""
Generate realistic test PDFs for TabuApp v2 testing.
Creates: Tabu extract, Planning document, Economic report.
Based on the user's feasibility data:
- 2 blocks, 5 parcels, 5 buildings, 25 apartments
- 1500 sqm blue line area, 2000 sqm total apartment area
- FAR multiplier 3.5
"""

import fitz  # PyMuPDF

FONT_SIZE = 10
LINE_HEIGHT = 14
MARGIN_TOP = 50
MARGIN_RIGHT = 550  # RTL - start from right
MARGIN_LEFT = 40


def create_pdf(filename: str, lines: list[str]):
    """Create a PDF with RTL Hebrew text."""
    doc = fitz.open()
    page = doc.new_page(width=595, height=842)  # A4
    y = MARGIN_TOP

    for line in lines:
        if y > 790:
            page = doc.new_page(width=595, height=842)
            y = MARGIN_TOP

        if line.startswith("==="):
            # Section divider
            page.draw_line(
                fitz.Point(MARGIN_LEFT, y),
                fitz.Point(MARGIN_RIGHT, y),
                color=(0.3, 0.3, 0.3),
                width=0.5,
            )
            y += 8
            continue

        if line.startswith("###"):
            # Header
            text = line.replace("###", "").strip()
            page.insert_text(
                fitz.Point(MARGIN_LEFT, y),
                text,
                fontsize=14,
                fontname="helv",
                color=(0.1, 0.1, 0.4),
            )
            y += LINE_HEIGHT + 6
            continue

        if line.startswith("##"):
            text = line.replace("##", "").strip()
            page.insert_text(
                fitz.Point(MARGIN_LEFT, y),
                text,
                fontsize=12,
                fontname="helv",
                color=(0.2, 0.2, 0.5),
            )
            y += LINE_HEIGHT + 4
            continue

        # Regular text
        page.insert_text(
            fitz.Point(MARGIN_LEFT, y),
            line,
            fontsize=FONT_SIZE,
            fontname="helv",
        )
        y += LINE_HEIGHT

    doc.save(filename)
    doc.close()
    print(f"Created: {filename}")


# ──────────────────────────────────────────────
# 1. TABU EXTRACT (Land Registry Document)
# ──────────────────────────────────────────────
tabu_lines = [
    "### NESACH TABU - Land Registry Extract",
    "### נסח טאבו - רשם המקרקעין",
    "",
    "Date of Issue: 02/03/2026",
    "Registry: Tel Aviv District",
    "===",
    "",
    "## Property Details - Block 6521",
    "",
    "Block (Gush): 6521",
    "Parcel (Helka): 45",
    "Area: 750 sqm",
    "Address: Herzl Street 12, Tel Aviv-Yafo",
    "City: Tel Aviv",
    "Street: Herzl",
    "Number: 12",
    "Land Type: Urban (Moshaa)",
    "",
    "===",
    "## Sub-Parcels and Owners - Block 6521, Parcel 45",
    "",
    "Sub-Parcel 1 | Floor 1 | Area: 60 sqm",
    "  Owner: David Cohen | ID: 012345678 | Share: 60/750",
    "",
    "Sub-Parcel 2 | Floor 1 | Area: 70 sqm",
    "  Owner: Sarah Levy | ID: 023456789 | Share: 70/750",
    "",
    "Sub-Parcel 3 | Floor 2 | Area: 80 sqm",
    "  Owner: Moshe Peretz | ID: 034567890 | Share: 80/750",
    "",
    "Sub-Parcel 4 | Floor 2 | Area: 90 sqm",
    "  Owner: Rachel Mizrachi | ID: 045678901 | Share: 90/750",
    "",
    "Sub-Parcel 5 | Floor 3 | Area: 100 sqm",
    "  Owner: Yossi Abramov | ID: 056789012 | Share: 100/750",
    "",
    "Total units in building: 5",
    "Total residential area: 400 sqm",
    "Building total area: 300 sqm (common)",
    "",
    "===",
    "## Property Details - Block 6522",
    "",
    "Block (Gush): 6522",
    "Parcel (Helka): 18",
    "Area: 750 sqm",
    "Address: Herzl Street 14, Tel Aviv-Yafo",
    "City: Tel Aviv",
    "Street: Herzl",
    "Number: 14",
    "Land Type: Urban (Moshaa)",
    "",
    "===",
    "## Sub-Parcels and Owners - Block 6522, Parcel 18",
    "",
    "Sub-Parcel 1 | Floor 1 | Area: 60 sqm",
    "  Owner: Avi Goldstein | ID: 067890123 | Share: 60/750",
    "",
    "Sub-Parcel 2 | Floor 1 | Area: 70 sqm",
    "  Owner: Miriam Katz | ID: 078901234 | Share: 70/750",
    "",
    "Sub-Parcel 3 | Floor 2 | Area: 80 sqm",
    "  Owner: Eli Shapira | ID: 089012345 | Share: 80/750",
    "",
    "Sub-Parcel 4 | Floor 2 | Area: 90 sqm",
    "  Owner: Noa Ben-David | ID: 090123456 | Share: 90/750",
    "",
    "Sub-Parcel 5 | Floor 3 | Area: 100 sqm",
    "  Owner: Uri Friedman | ID: 001234567 | Share: 100/750",
    "",
    "Total units in building: 5",
    "Total residential area: 400 sqm",
    "Building total area: 300 sqm (common)",
    "",
    "===",
    "## Summary Across All Parcels",
    "",
    "Total Blocks: 2 (6521, 6522)",
    "Total Parcels: 5",
    "Total Buildings: 5",
    "Total Apartments in Blue Line: 25",
    "Total Apartment Area in Blue Line: 2,000 sqm",
    "Total Blue Line Area (Land): 1,500 sqm",
    "",
    "===",
    "## Liens and Encumbrances",
    "",
    "Block 6521, Parcel 45:",
    "  Lien Type: Planning Restriction (Haarat Azhara)",
    "  Authority: Tel Aviv Municipality",
    "  Date: 15/03/2020",
    "  Details: Urban renewal area - Pinui Binui designated zone",
    "",
    "  Mortgage: Bank Leumi",
    "  Rank: 1",
    "  Amount: 850,000 NIS",
    "  Date: 01/06/2019",
    "  Borrower: David Cohen (Sub-Parcel 1)",
    "",
    "Block 6522, Parcel 18:",
    "  Lien Type: Planning Restriction",
    "  Authority: Tel Aviv Municipality",
    "  Date: 15/03/2020",
    "  Details: Urban renewal area - Pinui Binui designated zone",
    "",
    "===",
    "## Warnings (Haarot Azhara)",
    "",
    "Warning 1: Urban renewal plan pending - Tama 38/2 application filed",
    "  Date: 22/08/2023",
    "  Details: Pinui Binui project initiated for blocks 6521-6522",
    "",
    "Warning 2: Purchase agreement registered",
    "  Date: 10/01/2024",
    "  Details: Developer agreement with Eshkol Urban Renewal Ltd.",
    "",
    "===",
    "End of Tabu Extract",
    "Issued by: Rasham HaMekarke'in - Israel Land Registry",
]


# ──────────────────────────────────────────────
# 2. PLANNING DOCUMENT (Taba / Building Plan)
# ──────────────────────────────────────────────
planning_lines = [
    "### Urban Renewal Planning Document - Feasibility Study",
    "### תוכנית פינוי-בינוי - מסמך תכנוני",
    "",
    "Project: Herzl 12-14 Urban Renewal",
    "Location: Herzl Street, Tel Aviv-Yafo",
    "Plan Number: TA/2024/5521",
    "Date: February 2026",
    "Prepared by: Shikun & Binui Planning Division",
    "===",
    "",
    "## 1. Existing State (Matzav Nichnas)",
    "",
    "Total Blocks: 2",
    "Total Parcels: 5",
    "Total Buildings: 5",
    "Total Existing Apartments: 25",
    "Total Apartment Area: 2,000 sqm",
    "Total Blue Line Area (Land): 1,500 sqm",
    "",
    "Apartment Type Distribution (Existing):",
    "  Type 1: 60 sqm - 5 units",
    "  Type 2: 70 sqm - 5 units",
    "  Type 3: 80 sqm - 5 units",
    "  Type 4: 90 sqm - 5 units",
    "  Type 5: 100 sqm - 5 units",
    "",
    "===",
    "## 2. Planning Parameters (Proposed State)",
    "",
    "FAR Multiplier (Machpil Zchuyot): 3.5",
    "Returns Percent (Achuz Tmurot): 33%",
    "Average Apartment Size: 95 sqm",
    "Number of Floors Permitted: 8.5",
    "Coverage Above Ground: 70%",
    "Coverage Underground: 75%",
    "",
    "Blue Line Area: 1,500 sqm",
    "Total Floor Area (Shetach Ritzpa Kolel): 7,500 sqm",
    "Total New Units: 79",
    "Return Area Per Apartment: 12 sqm (additional to existing)",
    "",
    "Planning Stage: Approved Plan (Tochnit Me'usheret)",
    "",
    "===",
    "## 3. Building Program (Programa)",
    "",
    "Service Area Percentage: 20%",
    "Service Areas Total: calculated per building",
    "Total Above Ground Area: 8,925 sqm",
    "",
    "Floor Area Per Building: 525 sqm (typical floor)",
    "Number of Buildings: 2",
    "Floors Per Building: 8.5",
    "Above Ground Per Building: 4,463 sqm",
    "",
    "Development Land Area: 450 sqm (30% of site)",
    "Public/Commercial Area: 0 sqm",
    "Balcony Area Per Unit: 12 sqm",
    "",
    "===",
    "## 4. Parking Plan",
    "",
    "Parking Standard Ratio: 1.0 per unit",
    "Total Parking Spots Required: 87.5 (88)",
    "Gross Area Per Parking Space: 50 sqm",
    "Total Parking Area: 4,375 sqm",
    "Maximum Underground Floor Coverage: 75%",
    "Parking Floor Area: 1,125 sqm per level",
    "Number of Underground Parking Levels: 3.9 (4 levels)",
    "",
    "===",
    "## 5. Apartment Mix (Proposed)",
    "",
    "Return Apartments (Dirot Tmura):",
    "  Type 1: 72 sqm (60+12) - 5 units",
    "  Type 2: 82 sqm (70+12) - 5 units",
    "  Type 3: 92 sqm (80+12) - 5 units",
    "  Type 4: 102 sqm (90+12) - 5 units",
    "  Type 5: 112 sqm (100+12) - 5 units",
    "  Total Return: 25 units, 2,300 sqm",
    "",
    "Developer Apartments (Dirot Yazam):",
    "  Total Developer Units: 62.5 (63)",
    "  Total Developer Floor Area: 5,138 sqm",
    "  Average Developer Unit Size: 82.2 sqm",
    "",
    "Combination Ratio:",
    "  Return Floor Area: 2,300 sqm (31%)",
    "  Developer Floor Area: 5,138 sqm (69%)",
    "  Total Floor Area: 7,438 sqm (100%)",
    "",
    "===",
    "## 6. Typical Floor Area Constraints",
    "",
    "Typical Floor Area Minimum: 500 sqm",
    "Typical Floor Area Maximum: 600 sqm",
    "Apartments Per Floor Minimum: 4",
    "Apartments Per Floor Maximum: 6",
    "",
    "===",
    "## 7. Building Lines and Restrictions",
    "",
    "Building Lines Notes: 5m setback from Herzl Street, 3m from rear boundary.",
    "Adjacent buildings require 6m separation distance.",
    "Heritage facade preservation required on eastern elevation.",
    "",
    "Public Tasks Notes: Developer must contribute 200 sqm public garden.",
    "Sidewalk widening of 2m along Herzl Street frontage.",
    "Underground utility relocation required before construction.",
    "",
    "===",
    "End of Planning Document",
]


# ──────────────────────────────────────────────
# 3. ECONOMIC REPORT
# ──────────────────────────────────────────────
economic_lines = [
    "### Economic Feasibility Report",
    "### דוח כדאיות כלכלית - פינוי בינוי",
    "",
    "Project: Herzl 12-14 Urban Renewal",
    "Location: Herzl Street, Tel Aviv-Yafo",
    "Report Date: January 2026",
    "Prepared by: Appraisal & Consulting Group Ltd.",
    "===",
    "",
    "## 1. Construction Costs (per sqm)",
    "",
    "Residential Construction: 7,500 NIS/sqm",
    "Service Area Construction: 5,000 NIS/sqm",
    "Commercial Construction: 8,000 NIS/sqm",
    "Balcony Construction: 3,500 NIS/sqm",
    "Site Development: 1,200 NIS/sqm",
    "Parking Construction Total: 4,500,000 NIS",
    "",
    "===",
    "## 2. Additional Costs",
    "",
    "Betterment Levy (Hetel Hashbacha): 2,800,000 NIS",
    "Purchase Tax: 0 NIS (exempt under Pinui Binui)",
    "Planning & Consultants: 1,500,000 NIS",
    "Permits & Fees (Agrot): 800,000 NIS",
    "Electricity Connection: 350,000 NIS",
    "Bank Supervision: 600,000 NIS",
    "Engineering Management: 1,200,000 NIS",
    "Tenant Supervision: 400,000 NIS",
    "Management Overhead: 900,000 NIS",
    "Marketing & Advertising: 1,100,000 NIS",
    "Tenant Lawyer: 500,000 NIS",
    "Developer Lawyer: 450,000 NIS",
    "Initiation Fee: 300,000 NIS",
    "Rent Subsidy (Dirot Tmura): 3,600,000 NIS",
    "Evacuation Cost: 250,000 NIS",
    "Moving Expenses: 125,000 NIS",
    "Contingency (Biltam): 2,000,000 NIS",
    "Demolition: 1,500,000 NIS",
    "",
    "===",
    "## 3. Financial Parameters",
    "",
    "Construction Duration: 36 months",
    "Financing Interest Rate: 5.5%",
    "VAT Rate: 17%",
    "CPI Linkage: 3.5%",
    "",
    "===",
    "## 4. Revenue Parameters",
    "",
    "Residential Sale Price: 42,000 NIS/sqm",
    "Commercial Sale Price: 35,000 NIS/sqm",
    "Parking Price Per Unit: 180,000 NIS",
    "Storage Unit Price: 15,000 NIS/sqm",
    "",
    "Sales Pace: 4 units per month",
    "Marketing Discount: 2.5%",
    "",
    "Price Per Unit By Type:",
    "  3 Rooms (75 sqm): 3,150,000 NIS",
    "  4 Rooms (95 sqm): 3,990,000 NIS",
    "  5 Rooms (120 sqm): 5,040,000 NIS",
    "  Penthouse (140 sqm): 6,300,000 NIS",
    "",
    "===",
    "## 5. Apartment Mix - Developer Units",
    "",
    "3 Rooms: 20 units (32%)",
    "4 Rooms: 25 units (40%)",
    "5 Rooms: 12 units (19%)",
    "Penthouse: 6 units (9%)",
    "Total: 63 units (100%)",
    "",
    "===",
    "## 6. Revenue Projection",
    "",
    "Total Residential Revenue: 259,000,000 NIS",
    "Total Commercial Revenue: 0 NIS",
    "Total Parking Revenue: 15,840,000 NIS",
    "Gross Revenue: 274,840,000 NIS",
    "Net Revenue (after marketing discount): 267,969,000 NIS",
    "",
    "===",
    "## 7. Cost Summary",
    "",
    "Total Construction Costs: 65,000,000 NIS",
    "Total Soft Costs: 14,475,000 NIS",
    "Total Tenant Costs: 4,975,000 NIS",
    "Betterment & Levies: 3,600,000 NIS",
    "Financing Costs: 8,500,000 NIS",
    "Total Costs (excl. VAT): 96,550,000 NIS",
    "VAT: 16,413,500 NIS",
    "Total Costs (incl. VAT): 112,963,500 NIS",
    "",
    "===",
    "## 8. Profitability Analysis",
    "",
    "Expected Developer Profit: 155,005,500 NIS",
    "Profitability Rate: 57.9%",
    "IRR (Internal Rate of Return): 32.4%",
    "NPV (at 8% discount): 98,500,000 NIS",
    "",
    "===",
    "## 9. Sensitivity Analysis",
    "",
    "Revenue -10%: Profit = 128,208,600 NIS (47.8%)",
    "Revenue -20%: Profit = 101,411,700 NIS (37.8%)",
    "Costs +10%: Profit = 143,709,150 NIS (53.7%)",
    "Costs +20%: Profit = 132,412,800 NIS (49.4%)",
    "",
    "===",
    "## 10. Conclusion",
    "",
    "The project demonstrates strong economic viability with a profitability",
    "rate of 57.9% and IRR of 32.4%. Even under pessimistic scenarios",
    "(revenue -20%, costs +20%), the project remains profitable at 25.3%.",
    "Recommendation: Proceed with development.",
    "",
    "===",
    "End of Economic Report",
    "",
    "Signed: Dr. Amit Rosenfeld, Senior Appraiser",
    "License No. 5521-TA",
]

if __name__ == "__main__":
    create_pdf("tabu_extract_herzl_12_14.pdf", tabu_lines)
    create_pdf("planning_document_herzl_renewal.pdf", planning_lines)
    create_pdf("economic_feasibility_report.pdf", economic_lines)
    print("\nAll 3 test PDFs created successfully!")
